go1:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 1000  

    # FL Controllers ---------------------------------------
    FL_controller:
        type: effort_controllers/JointTrajectoryController
        joints: 
            - FL_hip_joint
            - FL_thigh_joint
            - FL_calf_joint
        gains:
            FL_hip_joint: {p: 100.0, i: 0.0, d: 5.0}
            FL_thigh_joint: {p: 300.0, i: 0.0, d: 8.0}
            FL_calf_joint: {p: 300.0, i: 0.0, d: 8.0}

    # FR Controllers ---------------------------------------
    FR_controller:
        types: effort_controllers/JointTrajectoryController
        joints: 
            - FR_hip_joint
            - FR_thigh_joint
            - FR_calf_joint
        gains:
            FR_hip_joint: {p: 100.0, i: 0.0, d: 5.0}
            FR_thigh_joint: {p: 300.0, i: 0.0, d: 8.0}
            FR_calf_joint: {p: 300.0, i: 0.0, d: 8.0}

    # RL Controllers ---------------------------------------
    RL_controller:
        type: effort_controllers/JointTrajectoryController
        joints: 
            - RL_hip_joint
            - RL_thigh_joint
            - RL_calf_joint
        gains:
            RL_hip_joint: {p: 100.0, i: 0.0, d: 5.0}
            RL_thigh_joint: {p: 300.0, i: 0.0, d: 8.0}
            RL_calf_joint: {p: 300.0, i: 0.0, d: 8.0}

    # RR Controllers ---------------------------------------
    RR_controller:
        type: effort_controllers/JointTrajectoryController
        joints: 
            - RR_hip_joint
            - RR_thigh_joint
            - RR_calf_joint
        gains:
            RR_hip_joint: {p: 100.0, i: 0.0, d: 5.0}
            RR_thigh_joint: {p: 300.0, i: 0.0, d: 8.0}
            RR_calf_joint: {p: 300.0, i: 0.0, d: 8.0}
